// data/productsData.js

const initialProducts = [
    { name: 'แป้งว่าว', price: '38฿',type:'วัตถุดิบ', quantity: 1, image: '/images/แป้งว่าว.jpeg' },
    { name: 'แป้งหงส์ขาว', price: '41฿',type:'วัตถุดิบ', quantity: 1, image: '/images/แป้งหงส์.jpeg' },
    { name: 'แป้งพัด', price: '49฿',type:'วัตถุดิบ', quantity: 1, image: '/images/แป้งพัด.jpeg' },
    { name: 'แป้งบัวแดง', price: '38฿',type:'วัตถุดิบ', quantity: 1, image: '/images/แป้งบัวแดง.jpeg' },
    { name: 'น้ำตาลทรายแดง มิตรผล 1 กก.', price: '41฿',type:'วัตถุดิบ', quantity: 1, image: '/images/ทรายแดงมิตรผล.jpeg' },
    { name: 'ชาตรามือ ฉลากแดง 400 ก.', price: '74฿',type:'วัตถุดิบ', quantity: 1, image: '/images/ชาตรามือแดง.jpeg' },
    { name: 'ชาตรามือ ชาเขียว 200 ก.', price: '74฿',type:'วัตถุดิบ', quantity: 1, image: '/images/ชาตรามือเขียว.jpeg' },
    { name: 'ชาตรามือ ฉลากทอง 400 ก.', price: '110฿',type:'วัตถุดิบ', quantity: 1, image: '/images/ชาตรามือทอง.jpeg' },
    { name: 'ฮีโร่ถุงขยะดำหนา 28x36', price: '70฿',type:'บรรจุภัณฑ์', quantity: 1, image: '/images/ฮีโร่ถุงขยะหนา 28x36.jpeg' },
    { name: 'ฮีโร่ถุงขยะดำหนา 24x30 1 กก.', price: '70฿',type:'บรรจุภัณฑ์', quantity: 1, image: '/images/ฮีโร่ถุงขยะหนา 24x30 1 กก.jpeg' },
    { name: 'ฮีโร่ถุงขยะหนา 30x40 50 ถุง.', price: '70฿',type:'บรรจุภัณฑ์', quantity: 1, image: '/images/ฮีโร่ถุงขยะหนา 30x40 50 ถุง.jpeg' },
    { name: 'แก้ววิสกี้ Ocean 340 ml', price: '35฿',type:'บรรจุภัณฑ์', quantity: 1, image: '/images/แก้ววิสกี้ Ocean 340 ml.jpg' },
    { name: 'กระทะจรวด 36 ซม.', price: '289฿',type:'เครื่องครัว', quantity: 1, image: '/images/กระทะจรวด 36.jpg' },
    { name: 'แก้วน้ำ Ocean 245 ml', price: '10฿',type:'บรรจุภัณฑ์', quantity: 1, image: '/images/แก้วน้ำ High ball 245 ml.jpg' },
    { name: 'แก้วน้ำ Ocean Patio 290 ml', price: '20฿',type:'บรรจุภัณฑ์', quantity: 1, image: '/images/PATIO HI BALL 290 ml.jpg' },
    { name: 'แก้วน้ำ LONG DRINK 415 ml',type:'บรรจุภัณฑ์', price: '35฿', quantity: 1, image: '/images/CHARISMA LONG DRINK.jpg' },
    { name: 'แก้วน้ำ SAN MARINO 290 ml', price: '35฿',type:'บรรจุภัณฑ์', quantity: 1, image: '/images/San MARIONO ROCK 290 ml.jpg' },
    { name: 'ซันไลต์เลมอน เทอร์โบ 3.2 ลิตร', price: '155฿',type:'อื่นๆ', quantity: 1, image: '/images/ซันไลต์ 3.2 ลิตร.jpeg' },
    { name: 'ซันไลต์พลัส แอนตี้แบค 2.8 ลิตร', price: '155฿',type:'อื่นๆ', quantity: 1, image: '/images/ซันไลต์พลัส แอนตี้แบค 2.8 ลิตร.jpeg' },
    { name: 'ถ้วยฟอยด์ 3001', price: '155฿',type:'บรรจุภัณฑ์', quantity: 1, image: '/images/ถ้วย3001.jpg'},
    { name: 'ถ้วยฟอยด์ 3003', price: '155฿',type:'บรรจุภัณฑ์', quantity: 1, image: '/images/3003ชมพู.jpg'},
    { name: 'ถ้วยฟอยด์ 3006 (200 มล.)', price: '155฿',type:'บรรจุภัณฑ์', quantity: 1, image: '/images/ฟอย3006.jpg'},
    { name: 'ถ้วยฟอยด์ 3007 (400 มล.)', price: '155฿',type:'บรรจุภัณฑ์', quantity: 1, image: '/images/ฟอย3007.png'},
    { name: 'ถ้วยฟอย 4001 ไม่มีลาย', price: '32฿',type:'อื่นๆ', quantity: 1, image: '/images/ฟอย4001.png'},
    { name: 'ถ้วยฟอย 4001 ชมพูจุด', price: '32฿',type:'อื่นๆ', quantity: 1, image: '/images/ฟอย4001ชมพู.png'},
    { name: 'ถ้วยฟอยด์ 4003', price: '155฿',type:'บรรจุภัณฑ์', quantity: 1, image: '/images/ถ้วย4003.jpg'},
    { name: 'ถ้วยฟอยด์ 4003 Rose Gold', price: '155฿',type:'บรรจุภัณฑ์', quantity: 1, image: '/images/ฟอย4003Rosegold.png'},
    { name: 'ถ้วยฟอยด์ 4003 ชมพู', price: '155฿',type:'บรรจุภัณฑ์', quantity: 1, image: '/images/ถ้วย4003 หินอ่อนชมพู.jpg'},
    { name: 'ถ้วยฟอยด์ 4003 ลายวัว', price: '155฿',type:'บรรจุภัณฑ์', quantity: 1, image: '/images/ถ้วย4003 ลายวัว.jpg'},
    { name: 'ถ้วยฟอยด์ 4003 ลายวัวชมพู', price: '155฿',type:'บรรจุภัณฑ์', quantity: 1, image: '/images/ถ้วย4003 ลายวัวชมพู.jpg'},
    { name: 'ถ้วยฟอยด์ 4004', price: '155฿',type:'บรรจุภัณฑ์', quantity: 1, image: '/images/ฟอย4004.png'},
    { name: 'ถ้วยฟอยด์ Gold 4004', price: '155฿',type:'บรรจุภัณฑ์', quantity: 1, image: '/images/ฟอย4004Gold.png'},
    { name: 'ถ้วยฟอยด์ Rose Gold 4004', price: '155฿',type:'บรรจุภัณฑ์', quantity: 1, image: '/images/ฟอย4004RoseGold.png'},
    { name: 'กระทงกระดาษ เลม่อน 2816', price: '155฿',type:'บรรจุภัณฑ์', quantity: 1, image: '/images/กระทงเลม่อน.png'},
    { name: 'กระทงกระดาษ เบเกอรี่ 2816', price: '155฿',type:'บรรจุภัณฑ์', quantity: 1, image: '/images/กระทงเบเกอรี่.png'},
    { name: 'กระทงกระดาษ หัวใจ 3219', price: '155฿',type:'บรรจุภัณฑ์', quantity: 1, image: '/images/กระทงกระดาษหัวใจ.png'},
    { name: 'กระทงกระดาษ สตรอเบอรี่', price: '155฿',type:'บรรจุภัณฑ์', quantity: 1, image: '/images/กระทงสตรอ.png'},
    { name: 'กระทงกระดาษ เลม่อน 3220', price: '155฿',type:'บรรจุภัณฑ์', quantity: 1, image: '/images/กระทงเลม่อน.png'},
    { name: 'กระทงกระดาษ เบเกอรี่ 3220', price: '155฿',type:'บรรจุภัณฑ์', quantity: 1, image: '/images/กระทงเบเกอรี่.png'},
    { name: 'เอสพี ตรา UFM 100 g', price: '155฿',type:'วัตถุดิบ', quantity: 1, image: '/images/SP100G.png'},
    { name: 'เอสพี ตรา UFM 1 kg', price: '155฿',type:'วัตถุดิบ', quantity: 1, image: '/images/SP1KG.png'},
    { name: 'ผงโกโก้ริช สีเข้ม 500 ก.', price: '190฿',type:'อื่นๆ', quantity: 1, image: '/images/โกโก้ริช สีเข้ม 500 ก.jpeg'},
    { name: 'ผงโกโก้ริช สีปกติ 500 ก.', price: '190฿',type:'อื่นๆ', quantity: 1, image: '/images/โกโก้ริช สีอ่อน 500 ก.jpeg'},
    { name: 'ผงโกโก้ทิวลิป สีเข้ม 440 ก.', price: '180฿',type:'อื่นๆ', quantity: 1, image: '/images/ผงโกโก้ทิวลิป สีเข้ม 440 ก.jpeg'},
    { name: 'ผงโกโก้แวนฮูเต็น 400 ก.', price: '180฿',type:'อื่นๆ', quantity: 1, image: '/images/ผงโกโก้ทิวลิป สีเข้ม 440 ก.jpeg'},
  
    
  ];
  
  export default initialProducts;
  